version: '3.7'

services:
  joomla:
    image: joomla
    restart: always
    volumes:
      - ./.docker/www:/var/www/html
    ports:
      - ${JOOMLA_PORT}:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
      - ./.docker/db/initdb:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: joomla

  adminer:
    image: swa-adminer:4.6
    build: ./.docker/adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  util:
    image: swa-util:0001
    build:
      context: ./.docker/util
      dockerfile: Dockerfile
    volumes:
      - ./.docker/www:/var/www/html
      - ./:/swa

volumes:
  db-volume:
