version: '3.7'

services:
  joomla:
    image: joomla
    restart: always
    volumes:
      - ${JOOMLA_PATH}:/var/www/html
    ports:
      - ${JOOMLA_PORT}:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.6
    build: ./.docker/adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  db-volume:
