version: '3.7'

services:
  joomla:
    image: joomla:3
    restart: always
    depends_on:
      - db
    volumes:
      - ./.docker/www:/var/www/html
      - ./.docker/configuration.php:/var/www/html/configuration.php
      - ./src/administrator:/var/www/html/administrator/components/com_swa
      - ./src/site:/var/www/html/components/com_swa
      - ./src/plugin:/var/www/html/plugins/swa/viewlevels
      - ./.docker/www-logs:/var/logs/joomla
    ports:
      - ${JOOMLA_PORT:-5555}:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example
      JCONFIG_STRIPE_PUBLISHABLE_KEY: ${JCONFIG_STRIPE_PUBLISHABLE_KEY}
      JCONFIG_STRIPE_SECRET_KEY: ${JCONFIG_STRIPE_SECRET_KEY}

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
      - ./.docker/db/initdb:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT:-5557}:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: joomla

  adminer:
    image: swa-adminer:4.6
    depends_on:
      - db
    build: ./.docker/adminer
    restart: always
    ports:
      - ${ADMINER_PORT:-5556}:8080

volumes:
  db-volume:
